logging.level.org.springframework.r2dbc=INFO
logging.level.io.r2dbc=INFO
logging.level.org.wildcloud=INFO
spring.application.name=wildcloud_backend
spring.config.import=optional:file:src/main/java/org/wildcloud/wildcloud_backend/config/.env[.properties]


spring.security.user.name=${POSTGRES_USERNAME}
spring.security.user.password=${POSTGRES_PASSWORD}

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.url=jdbc:postgresql://localhost:5432/postgres
spring.flyway.user=${POSTGRES_USERNAME}
spring.flyway.password=${POSTGRES_PASSWORD}

spring.flyway.clean-disabled=false
spring.flyway.clean-on-startup=true


spring.r2dbc.url=r2dbc:postgresql://localhost:5432/postgres
spring.r2dbc.username=${POSTGRES_USERNAME}
spring.r2dbc.password=${POSTGRES_PASSWORD}
spring.r2dbc.properties.sslMode=disable
spring.r2dbc.properties.tcpKeepAlive=true
spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initialSize=5
spring.r2dbc.pool.maxSize=10

#spring.sql.init.mode=always
#spring.sql.init.schema-locations=classpath:schema-drop.sql,classpath:schema.sql

