logging.level.org.springframework.r2dbc=INFO
logging.level.io.r2dbc=INFO
logging.level.org.wildcloud=INFO
spring.application.name=wildcloud_backend
spring.config.import=optional:file:src/main/java/org/wildcloud/wildcloud_backend/config/.env[.properties]


# Flyway Configuration
spring.flyway.url=jdbc:postgresql://localhost:5432/postgres
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.out-of-order=true
spring.flyway.clean-disabled=false

# Flyway logging
spring.flyway.logging=true
logging.level.org.flywaydb=DEBUG


# DB credentials
spring.security.user.name=${POSTGRES_USERNAME}
spring.security.user.password=${POSTGRES_PASSWORD}
spring.flyway.user=${POSTGRES_USERNAME}
spring.flyway.password=${POSTGRES_PASSWORD}
spring.flyway.placeholders.username=${POSTGRES_USERNAME}
spring.flyway.placeholders.password=${POSTGRES_PASSWORD}




# R2DBC Configuration
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/postgres
spring.r2dbc.username=${POSTGRES_USERNAME}
spring.r2dbc.password=${POSTGRES_PASSWORD}
spring.r2dbc.properties.sslMode=disable
spring.r2dbc.properties.tcpKeepAlive=true
spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initialSize=5
spring.r2dbc.pool.maxSize=10

# Set to always to enable automatic schema creation with Hibernate (doesnt work with flyway)
spring.sql.init.mode=never

